spring:
  profiles: master
  application:
    name: EurekaMaster
server:
  port: 10237

eureka:
  instance:
    hostname: master
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false
    appname: EurekaMaster
  client:
    # Enabled Register Self To Server
    register-with-eureka: true
    # Enabled Fetch Server
    fetch-registry: true
    # Set Default Address
    serviceUrl:
      defaultZone: http://blogmanager:123456@backup1:10238/eureka/,http://blogmanager:123456@backup2:10239/eureka/
#      defaultZone: http://blogmanager:123456@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 4000
    renewal-percent-threshold: 0.49
    enable-self-preservation: true

